### ISSUE TITLE
Adding sensor entities to HA interration

### ISSUE THREAD

**Issue by Pi-Markku** [jnsgruk/pytouchlinesl#3]
Hello, and thanks for the Home Assistant intergation of Roth Touchline SL

Is it possible to add actual temperature and humidity values also as sensor entities?

**Comment by jnsgruk** [comment]
Hi! Sorry for the delayed response. I've been travelling with work.

I think this should be possible, but probably best to file an issue on the Home Assistant repo, or a feature request here: https://community.home-assistant.io/c/feature-requests/13

The feature won't be implemented in this repo, but rather in the home assistant integration itself, so I'll close this for now.
